# Site settings
title: Unofficial Waterloo USA Full-time Guide 
email: fulltime@stephenholiday.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/waterloo-fulltime-guide" # the subpath of your site, e.g. /blog/
url: "https://stephenholiday.com" # the base hostname & protocol for your site
github_username: sholiday

# Build settings
markdown: kramdown
